### ISSUE TITLE
Some quick patches

### ISSUE THREAD

**Issue by bjmnbraun** [psewar/Raidfelden.Discord.Bot#3]
Some quick patches we made on our deployment. See attached tar gz for the patches, they are all small. Choose to mainline them if you like.

commit ee5d3cf0cf0ecf950b4f7ec3d3394483191fe876
Date:   Tue Jul 24 15:30:20 2018 -0700

    Improvements to interaction. Now supports up to 36 options and doesn't react itself, instead the user must react with the right emoji. This reduces discord rate limiting effects.

commit 64f24e61490a4950c848c2ef6f9def493f464f98
Date:   Tue Jul 24 15:29:26 2018 -0700

    Typo fix (Tank you)

commit ceebaf753b125aee41aa3026d0fc5a3f54ce834a
Date:   Tue Jul 24 15:29:04 2018 -0700

    Bugfix to OCR when using channel wildcard

commit ecd4b31670aef63738ffe91b950f006344199307
Date:   Tue Jul 24 15:28:02 2018 -0700

    Minor to channel name wildcard handling

[pokefairy-patches-2018-07.tar.gz](https://github.com/psewar/Raidfelden.Discord.Bot/files/2225716/pokefairy-patches-2018-07.tar.gz)

**Comment by psewar** [comment]
Cool, thank you very much for the patches, as I'm back now from my holidays I started to apply the patches provided by you.
I'll close this issue as I already applied all those patches with my latest commits.
