### ISSUE TITLE
Raid submission does not update the LastModified column in the forts_sightings table

### ISSUE THREAD

**Issue by bjmnbraun** [psewar/Raidfelden.Discord.Bot#4]
Currently raid submission through the bot does not modify the LastModified column in the forts sightings table, therefore the map (say, PMSF) does not update properly.

On saving a Raids entity, the monocle database handler should also generate an event to update the LastModified column of the forts_sighting for the fort that the Raid corresponds to. Otherwise PMSF does not update the icon for the gym.

Arguably, this takes a bit of work to set up, in the current codebase.

**Comment by bjmnbraun** [comment]
Wrote up a patch that fixes this. It turns out that novabot notifications don't work properly either unless you do this because of the sql query used in novabot so fixing this was a priority for us.

I learned entity framework, yay!

[patch.tar.gz](https://github.com/psewar/Raidfelden.Discord.Bot/files/2230171/patch.tar.gz)

**Comment by psewar** [comment]
Perfect that was also an issue on my personal todo-list, thank you for fixing it :)
