### ISSUE TITLE
[Patch] IOS smart punctuation introduces non-ascii quotes

### ISSUE THREAD

**Issue by bjmnbraun** [psewar/Raidfelden.Discord.Bot#6]
IOS devices don't insert ascii quotes when using quotes, unfortunately. They use fancier look-alikes of quotes that are slanted.

This patch modifies all messages into the bot to replace such lookalikes with ascii quotes

[0001-Handle-IOS-quotes.patch.zip](https://github.com/psewar/Raidfelden.Discord.Bot/files/2263952/0001-Handle-IOS-quotes.patch.zip)

**Comment by psewar** [comment]
Yeah that was also an issue that people frequently ran into.
As a workaround they could disable the smart punctuation feature in the IOS settings, but fixing it in the bot is of course the best option. :)
I applied your patch and will close this issue now, thank you
